version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: easy-web-backend
    ports:
      - "8080:8080" # Spring Boot デフォルトポート
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/easy-web
      dockerfile: Dockerfile
    container_name: easy-web-frontend
    ports:
      - "3000:3000" # Next.js デフォルトポート
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:8080/graphql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

